flowchart TB
    A([The Strapi application starts.]) --> B{"register()"} 
    B -- The Strapi application is setup. --> C
    C{"bootstrap()"} -- The Strapi back-end server starts. --> D
    D(Request)
    D
    click B "#register"
    click C "#bootstrap"
    click D "/cms/backend-customization/requests-responses"