const path=require("path"),http=require("http"),fs=require("fs");
const {chromium}=require("/Users/piwi/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core");
const DIR=__dirname,PORT=8675;
const MIME={".html":"text/html",".css":"text/css",".js":"text/javascript",".json":"application/json",".png":"image/png",".jpg":"image/jpeg",".svg":"image/svg+xml",".gif":"image/gif",".webp":"image/webp"};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";
fs.readFile(path.join(DIR,p),(e,d)=>{if(e){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":MIME[path.extname(p).toLowerCase()]||"application/octet-stream"});res.end(d);});});
(async()=>{await new Promise(r=>server.listen(PORT,r));
const b=await chromium.launch();const errs=[];
const p=await b.newPage({viewport:{width:1440,height:900}});
p.on("console",m=>{if(m.type()==="error")errs.push(m.text())});
p.on("pageerror",e=>errs.push(String(e)));
const base="http://localhost:"+PORT+"/index.html";
await p.goto(base+"#/quais",{waitUntil:"domcontentloaded"});
await p.waitForSelector(".carriage");await p.waitForTimeout(700);
await p.screenshot({path:path.join(DIR,"shot-quais.jpg"),type:"jpeg",quality:80});
await p.goto(base+"#/gare",{waitUntil:"domcontentloaded"});
await p.waitForSelector(".brow");await p.waitForTimeout(2600);
await p.screenshot({path:path.join(DIR,"shot-world.jpg"),type:"jpeg",quality:80});
await p.goto(base+"#/cms/api/document-service",{waitUntil:"domcontentloaded"});
await p.waitForSelector(".paper");await p.waitForTimeout(900);
await p.screenshot({path:path.join(DIR,"shot-read.jpg"),type:"jpeg",quality:80});
await p.goto(base+"#/legende",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(500);
await p.screenshot({path:path.join(DIR,"shot-legende.jpg"),type:"jpeg",quality:70});
await b.close();server.close();
console.log("errors:",errs.length);errs.slice(0,10).forEach(e=>console.log(e));
})().catch(e=>{console.error(e);process.exit(2)});
