name: Documentation Bug Report
about: Create a report to help us improve the Strapi documentation.
title: "[Bug]: "
labels: "type: bug, status: pending reproduction"
issue_body: true
inputs:
- type: input
  attributes:
    label: Link to the documentation page or resource
    required: true
    placeholder: https://strapi.io/documentation/developer-docs/latest/somepage.html
- type: textarea
  attributes:
    label: Describe the bug
    required: true
    placeholder: "A clear and concise description of what the bug is."
- type: textarea
  attributes:
    label: Additional context
    required: false
    placeholder: "Add any other context about the problem here."
- type: textarea
  attributes:
    label: Suggested improvements or fixes
    required: false
    placeholder: "A clear and concise description of what you want to happen."
- type: textarea
  attributes:
    label: Related issue(s)/PR(s)
    required: false
    placeholder: "Let us know if this is related to any issue/pull request."
