name: Documentation Request
about: Suggest a new part of the documentation we are missing!
title: "[Request]: "
labels: "type: doc request"
issue_body: false
inputs:
- type: textarea
  attributes:
    label: Summary
    required: true
    placeholder: Quick summary what's this documentation request about.
- type: textarea
  attributes:
    label: Why is it needed?
    required: true
    placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
- type: textarea
  attributes:
    label: Suggested solution(s)
    required: false
    placeholder: "A clear and concise description of what you want to happen."
- type: textarea
  attributes:
    label: Related issue(s)/PR(s)
    required: false
    placeholder: "Let us know if this is related to any issue/pull request."
