// Central list of localized prompts used by AI toolbar actions.
// Contributors can add new language codes (ISO language tag) or adjust translations here.
// Keep the {{url}} placeholder intact -- it will be replaced with the current document URL.

export const aiPromptTemplates = {
  'ar': 'اقرأ من {{url}} حتى أتمكن من طرح أسئلة حوله.',
  'ay': '{{url}} uñt’asma ukhamarusa jupanxata jiskt’añataki.',
  'be': 'Прачытай {{url}}, каб я мог задаваць пытанні пра гэта.',
  'bg': 'Прочети {{url}}, за да мога да задавам въпроси за него.',
  'bn': '{{url}} থেকে পড়ুন যাতে আমি এর সম্পর্কে প্রশ্ন করতে পারি।',
  'bs': 'Pročitaj {{url}} kako bih mogao postavljati pitanja o tome.',
  'ca': 'Llegeix {{url}} perquè pugui fer preguntes sobre això.',
  'crk': 'Ka-pîhtokê {{url}} mîna nika isiyihkêw pimipahtâw.',
  'cs': 'Přečti si {{url}}, abych mohl pokládat otázky.',
  'cy': 'Darllen {{url}} fel y gallaf ofyn cwestiynau amdano.',
  'da': 'Læs {{url}}, så jeg kan stille spørgsmål om det.',
  'de': 'Lies {{url}}, damit ich Fragen dazu stellen kann.',
  'el': 'Διάβασε το {{url}} ώστε να μπορώ να κάνω ερωτήσεις σχετικά.',
  'en': 'Read from {{url}} so I can ask questions about it.',
  'es': 'Lee {{url}} para que pueda hacer preguntas al respecto.',
  'et': 'Loe {{url}}, et saaksin selle kohta küsimusi esitada.',
  'fa': 'از {{url}} بخوان تا بتوانم در مورد آن سؤال بپرسم.',
  'fi': 'Lue {{url}}, jotta voin esittää siitä kysymyksiä.',
  'fil': 'Basahin ang {{url}} para makapagtanong ako tungkol dito.',
  'fr': 'Lis {{url}} pour que je puisse poser des questions à son sujet.',
  'ga': 'Léigh {{url}} ionas go mbeidh mé in ann ceisteanna a chur faoi.',
  'gn': 'Emoñeʼẽ {{url}} ikatu hag̃ua porandu chupe rehe.',
  'gu': '{{url}} વાંચો જેથી હું તેના વિશે પ્રશ્નો પૂછી શકું.',
  'haw': 'E heluhelu i {{url}} i hiki iaʻu ke nīnau e pili ana iā ia.',
  'he': 'קרא את {{url}} כדי שאוכל לשאול עליו שאלות.',
  'hi': '{{url}} पढ़ें ताकि मैं इसके बारे में प्रश्न पूछ सकूँ।',
  'hr': 'Pročitaj {{url}} kako bih mogao postavljati pitanja o tome.',
  'ht': 'Li {{url}} pou mwen ka poze kesyon sou li.',
  'hu': 'Olvasd el a {{url}} tartalmát, hogy kérdéseket tehessek fel róla.',
  'id': 'Baca {{url}} agar saya bisa mengajukan pertanyaan tentangnya.',
  'is': 'Lestu {{url}} svo ég geti spurt spurninga um það.',
  'it': 'Leggi {{url}} così posso fare domande al riguardo.',
  'ja': '{{url}} を読んで、質問できるようにしてください。',
  'jv': 'Waca {{url}} supaya aku bisa takon babagan iki.',
  'kk': '{{url}} оқыңыз, сонда мен оған қатысты сұрақтар қоя аламын.',
  'km': 'អាន {{url}} ដើម្បីឲ្យខ្ញុំអាចសួរពីវាបាន.',
  'kn': '{{url}} ಓದಿ, ನಾನು ಅದಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಲು ಸಾಧ್ಯವಾಗಲಿ.',
  'ko': '{{url}} 를 읽어 보고 이에 대해 질문할 수 있게 해 주세요.',
  'ku': '{{url}} bixwîne da ku bikaribim li ser wî pirsên li dayim.',
  'ky': '{{url}} оку, ошондо мен андан суроолор бере алам.',
  'lb': 'Lies {{url}}, fir datt ech Froen doriwwer stelle kann.',
  'lo': 'ອ່ານ {{url}} ເພື່ອໃຫ້ຂ້ອຍສາມາດຖາມຄໍາຖາມກ່ຽວກັບມັນໄດ້.',
  'lt': 'Perskaityk {{url}}, kad galėčiau užduoti klausimus apie tai.',
  'lv': 'Izlasi {{url}}, lai es varētu uzdot jautājumus par to.',
  'mk': 'Прочитај {{url}} за да можам да поставувам прашања за тоа.',
  'ml': '{{url}} വായിക്കുക, അതിനെ കുറിച്ച് ഞാൻ ചോദ്യങ്ങൾ ചോദിക്കാനാകട്ടെ.',
  'mn': '{{url}}-с уншаад, үүнээс асуулт асуух боломж олгоорой.',
  'mr': '{{url}} वाचा म्हणजे मला त्याबद्दल प्रश्न विचारता येतील.',
  'ms': 'Baca {{url}} supaya saya boleh bertanya soalan mengenainya.',
  'mt': 'Aqra {{url}} sabiex inkun nista’ nistaqsi mistoqsijiet dwaru.',
  'my': '{{url}} ကိုဖတ်ပြီးအဲဒါအကြောင်း မေးမြန်းနိုင်အောင်လုပ်ပါ။',
  'nb': 'Les {{url}} slik at jeg kan stille spørsmål om det.',
  'ne': '{{url}} पढ्नुहोस् ताकि म यसको बारेमा प्रश्न सोध्न सकूँ।',
  'nl': 'Lees {{url}} zodat ik er vragen over kan stellen.',
  'nv': 'Háíshį́įgo {{url}} yiníłʼį́įł doo tʼáá chʼíyáán dóó baa akʼíníshííł níłchííʼ.',
  'oj': 'Na naa {{url}} ezhi-bimiwidoon omaa wikenh.',
  'pa': '{{url}} ਪੜ੍ਹੋ ਤਾਂ ਜੋ ਮੈਂ ਇਸ ਬਾਰੇ ਸਵਾਲ ਪੁੱਛ ਸਕਾਂ।',
  'pl': 'Przeczytaj {{url}}, żebym mógł zadawać pytania na ten temat.',
  'ps': '{{url}} ولوله، ترڅو زه وکولای شم په اړه يې پوښتنې وکړم.',
  'pt': 'Leia {{url}} para que eu possa fazer perguntas sobre isso.',
  'qu': '{{url}} ñawinchay, chaymanta tapuykuna ruriyta atispaq.',
  'ro': 'Citește {{url}} ca să pot pune întrebări despre el.',
  'ru': 'Прочитай {{url}}, чтобы я мог задавать вопросы по нему.',
  'si': '{{url}} කියවන්න, එතැන් පසු මට එය ගැන ප්‍රශ්න කිරීමට හැකිවනු ඇත.',
  'sk': 'Prečítaj si {{url}}, aby som o tom mohol klásť otázky.',
  'sl': 'Preberi {{url}}, da bom lahko postavljal vprašanja o tem.',
  'sq': 'Lexo {{url}} që të mund të bëj pyetje rreth tij.',
  'sr': 'Pročitaj {{url}} da bih mogao da постављam pitanja o tome.',
  'sv': 'Läs {{url}} så att jag kan ställa frågor om det.',
  'ta': '{{url}} படித்து நான் அதைப் பற்றி கேள்விகள் கேட்க முடியும்.',
  'te': '{{url}} చదవండి, దాని గురించి నేను ప్రశ్నలు అడగగలను.',
  'th': 'อ่าน {{url}} เพื่อที่ฉันจะได้ถามคำถามเกี่ยวกับมัน.',
  'tg': '{{url}}-ро бихон, то тавонам дар бораи он савол диҳам.',
  'tk': '{{url}}-i okaň, şonda men onuň barada sorag berip bilerin.',
  'tr': '{{url}} oku ki hakkında sorular sorabileyim.',
  'tt': '{{url}} укы, шуннан соң сораулар бирә алырмын.',
  'ug': '{{url}} نى ئوقۇپ چىقىڭ، شۇ توغۇرىدا سوئال سورىيالايمەن.',
  'uk': 'Прочитай {{url}}, щоб я міг ставити запитання про це.',
  'ur': '{{url}} پڑھیں تاکہ میں اس کے بارے میں سوالات پوچھ سکوں۔',
  'uz': '{{url}} ni o‘qing, shunda men undan savollar so‘ray olaman.',
  'vi': 'Đọc {{url}} để tôi có thể đặt câu hỏi về nó.',
  'zh': '请阅读 {{url}} 的内容，以便我能就其提出问题。',
};
