export const aiToolsConfig = {
  primaryActionId: 'copy-markdown',

  actions: [
    {
      id: 'copy-markdown',
      label: 'Copy Markdown',
      description: 'Copy the raw markdown content of this page',
      icon: 'copy',
      actionType: 'copy-markdown',
    },
    {
      id: 'view-llms',
      label: 'View LLMs.txt',
      description: 'Lightweight version for AI models',
      icon: 'file-text',
      actionType: 'navigate',
      url: '/llms.txt',
    },
    {
      id: 'view-llms-full',
      label: 'View LLMs-full.txt',
      description: 'Complete documentation for AI models',
      icon: 'file-text',
      actionType: 'navigate',
      url: '/llms-full.txt',
    },
    {
      id: 'open-chatgpt',
      label: 'Open with ChatGPT',
      // description: 'Open ChatGPT with a prompt about this page',
      icon: 'open-ai-logo',
      actionType: 'open-llm',
      targetUrl: 'https://chat.openai.com/',
      promptTemplate: 'Read from {{url}} so I can ask questions about it.',
      localizedPromptTemplates: {
        en: 'Read from {{url}} so I can ask questions about it.',
        zh: '请阅读 {{url}} 的内容，以便我能就其提出问题。',
        es: 'Lee {{url}} para que pueda hacer preguntas al respecto.',
        hi: '{{url}} पढ़ें ताकि मैं इसके बारे में प्रश्न पूछ सकूँ।',
        ar: 'اقرأ من {{url}} حتى أتمكن من طرح أسئلة حوله.',
        fr: 'Lis {{url}} pour que je puisse poser des questions à son sujet.',
        pt: 'Leia {{url}} para que eu possa fazer perguntas sobre isso.',
        bn: '{{url}} থেকে পড়ুন যাতে আমি এর সম্পর্কে প্রশ্ন করতে পারি।',
        ru: 'Прочитай {{url}}, чтобы я мог задавать вопросы по нему.',
        ja: '{{url}} を読んで、質問できるようにしてください。',
      },
      promptParam: 'prompt',
      openIn: '_blank',
    },
    {
      id: 'open-claude',
      label: 'Open with Claude',
      // description: 'Open Claude with a prompt about this page',
      icon: 'chat-teardrop-text',
      actionType: 'open-llm',
      targetUrl: 'https://claude.ai/new',
      promptTemplate: 'Read from {{url}} so I can ask questions about it.',
      localizedPromptTemplates: {
        en: 'Read from {{url}} so I can ask questions about it.',
        zh: '请阅读 {{url}} 的内容，以便我能就其提出问题。',
        es: 'Lee {{url}} para que pueda hacer preguntas al respecto.',
        hi: '{{url}} पढ़ें ताकि मैं इसके बारे में प्रश्न पूछ सकूँ।',
        ar: 'اقرأ من {{url}} حتى أتمكن من طرح أسئلة حوله.',
        fr: 'Lis {{url}} pour que je puisse poser des questions à son sujet.',
        pt: 'Leia {{url}} para que eu possa fazer perguntas sobre isso.',
        bn: '{{url}} থেকে পড়ুন যাতে నేను এর সম্পর্কে প্রশ্ন করতে পারি।',
        ru: 'Прочитай {{url}}, чтобы я мог задавать вопросы по нему.',
        ja: '{{url}} を読んで、質問できるようにしてください。',
      },
      includeDefaultPrompt: true,
      promptParam: 'q',
      openIn: '_blank',
    },
  ],
};
